### ISSUE TITLE
URL with user/pass does not work properly

### ISSUE THREAD

**Issue by arhi** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#12]
Snapshot URL is "http://rpi:xxx@192.168.1.11/tmpfs/snap.jpg"

log shows:

```
2019-03-24 17:56:25,156 - backoff - INFO - Backing off capture_jpeg(...) for 94.9s (InvalidURL: nonnumeric port: xxx@192.168.1.11')
2019-03-24 17:58:00,065 - backoff - INFO - Backing off capture_jpeg(...) for 105.6s (InvalidURL: nonnumeric port: 'xxx@192.168.1.11')
```

my pythong knowledge is limited but I'd say the problem is here: https://github.com/TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective/blob/ec5ba26957a84ae32c6233fe5908a4520d19e009/octoprint_thespaghettidetective_beta/webcam_capture.py#L24

normal urlparse works ok
```
Python 2.7.9 (default, Aug 13 2016, 17:56:53)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from urlparse import urlparse
>>> o = urlparse('http://rpi:xxx@192.168.1.11/tmpfs/snap.jpg')
>>> o.scheme
'http'
>>> o.port
>>> o.geturl()
'http://rpi:xxx@192.168.1.11/tmpfs/snap.jpg'
```

but urllib2 is library with a bug :(
```
>>> import urllib2
>>> urllib2.urlopen('http://rpi:xxx@192.168.1.11/tmpfs/snap.jpg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1166, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "/usr/lib/python2.7/httplib.py", line 741, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "/usr/lib/python2.7/httplib.py", line 783, in _get_hostport
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
httplib.InvalidURL: nonnumeric port: 'xxx@192.168.1.11'
>>>
```

**Comment by arhi** [comment]
note that octoprint fetches from this url without a problem

**Comment by arhi** [comment]
this is how octoprint fetch from that url:
https://github.com/foosel/OctoPrint/blob/112a8b9c8bf7f5895f6a29dbe3d98ea4d9e0f400/src/octoprint/timelapse.py#L611
